# -*- coding: utf-8 -*-
"""Generate exact English translations for diagnostic_engine UI strings."""
import json
import re
from pathlib import Path

ROOT = Path(r"C:\Users\bilaw\AndroidStudioProjects\fixxi")
DATASET = ROOT / "assets" / "Dataset.json"
OUT = ROOT / "lib" / "services" / "diagnosis_en.dart"

PHRASES = [
    ("foran band karein", "turn it off immediately"),
    ("foran band kar dein", "turn it off immediately"),
    ("khud mat karein", "do not do it yourself"),
    ("khud kuch mat karein", "do not try anything yourself"),
    ("bina safety ke", "without safety gear"),
    ("kam az kam", "at least"),
    ("khaas taur par", "especially"),
    ("qareeb na jayein", "do not go near it"),
    ("haath sookhe hon", "keep your hands dry"),
    ("plug nikaal dein", "unplug it"),
    ("thanda nahi kar raha", "not cooling"),
    ("bilkul chal nahi raha", "not turning on at all"),
    ("pani tapak raha hai", "water is leaking"),
    ("gandi filter", "dirty filter"),
    ("wapas lagayein", "put it back"),
    ("pani se dhoein", "wash with water"),
    ("sukha kar", "dry it and"),
    ("nikaal kar", "remove and"),
    ("band karke", "after switching off"),
    ("confirm karein", "confirm"),
    ("note karein", "note it down"),
    ("try karein", "try"),
    ("foran", "immediately"),
    ("dobara", "again"),
    ("khud", "yourself"),
]


def collect(engine):
    out = set()

    def add(x):
        if isinstance(x, str) and x.strip():
            out.add(x.strip())
        elif isinstance(x, list):
            for i in x:
                add(i)

    for h in engine.get("hazards", []):
        add(h.get("label"))
        add(h.get("safety"))
    add(engine.get("hazard_default_checks"))
    for a in engine.get("appliances", []):
        add(a.get("common_checks"))
        add(a.get("common_safety"))
        for f in a.get("faults", []):
            add(f.get("label"))
            add(f.get("checks"))
            add(f.get("safety"))
            for i in f.get("issues", []):
                add(i.get("title"))
                add(i.get("cause"))
    return sorted(out)


# Longest-first glossary of Roman Urdu → English (word/phrase).
GLOSS = {
    "foran band karein": "turn it off immediately",
    "foran band kar dein": "turn it off immediately",
    "band karein": "turn it off",
    "band kar dein": "turn it off",
    "on mat karein": "do not turn it on",
    "mat karein": "do not",
    "mat karwayein": "do not get it done",
    "mat charhein": "do not climb",
    "mat chhuein": "do not touch",
    "mat dalein": "do not pour",
    "mat lagayein": "do not connect",
    "mat kholein": "do not open",
    "mat jalayein": "do not light",
    "istemaal na karein": "do not use",
    "istemaal band": "stop using",
    "qareeb na jayein": "do not go near",
    "qareeb na khare hon": "do not stand near",
    "haath sookhe hon": "keep your hands dry",
    "haath bilkul sookhe hon": "keep your hands completely dry",
    "plug nikaal dein": "unplug it",
    "plug nikaal kar": "unplug and",
    "kam az kam": "at least",
    "khaas taur par": "especially",
    "ghar walon": "family members",
    "technician aane tak": "until the technician arrives",
    "licensed electrician": "a licensed electrician",
    "certified technician": "a certified technician",
    "certified HVAC technician": "a certified HVAC technician",
    "indoor filter": "indoor filter",
    "outdoor unit": "outdoor unit",
    "indoor unit": "indoor unit",
    "indoor ya outdoor panel": "indoor or outdoor panel",
    "andar capacitor charge rehta hai": "the capacitor inside may still be charged",
    "chhat/deewar par": "on the roof/wall",
    "bina safety ke": "without safety gear",
    "us tak mat charhein": "do not climb up to it",
    "thanda nahi kar raha": "not cooling",
    "cooling weak": "weak cooling",
    "gandi filter": "a dirty filter",
    "cooling 30–40% tak gira deti hai": "can cut cooling by 30–40%",
    "cooling 30-40% tak gira deti hai": "can cut cooling by 30–40%",
    "pani se dhoein": "wash with water",
    "sukha kar wapas lagayein": "dry it and put it back",
    "nikaal kar": "remove",
    "wapas lagayein": "put it back",
    "remote cool mode par ho": "set the remote to COOL mode",
    "fan/dry par nahi": "not FAN/DRY",
    "temperature 18–22°c set karein": "set the temperature to 18–22°C",
    "fan speed high par rakhein": "keep fan speed on HIGH",
    "on karein": "turn it on",
    "jagah clear karein": "keep the space clear",
    "hawa block na kare": "should not block the airflow",
    "fan ghoom raha hai": "fan is spinning",
    "na ghoome to": "if it is not spinning,",
    "compressor load nahi le raha": "the compressor is not loading",
    "darwaze/khirkiyan band karke": "close the doors/windows and",
    "grill se nikalne wali hawa": "the air coming from the grill",
    "check karein": "check",
    "gas refill khud kabhi mat karein": "never refill gas yourself",
    "yeh sirf": "this is only",
    "ka kaam hai": "job",
    "cover chadha kar": "with a cover on",
    "ac mat chalayein": "do not run the AC",
    "mcb / isolator": "MCB / isolator",
    "mcb / switch": "MCB / switch",
    "mcb / main switch": "MCB / main switch",
    "db board par jaa kar": "go to the DB board and",
    "confirm karein": "confirm",
    "naye cell daal kar dekhein": "put new cells in and check",
    "display aata hai ya nahi": "whether the display comes on",
    "doosra appliance laga kar test karein": "test with another appliance",
    "point mein current hai": "the point has power",
    "stabilizer laga ho to": "if a stabilizer is fitted,",
    "usay bypass karke direct try karein": "bypass it and try connecting directly",
    "beep ya blinking light": "a beep or blinking light",
    "uska pattern note karein": "note its pattern",
    "yeh error code hota hai": "this is an error code",
    "drain pipe": "drain pipe",
    "bahar wala sira dekhein": "check the outer end",
    "pani aa raha hai": "water is coming out",
    "bilkul ruk gaya hai": "it is fully blocked",
    "halka pressure/blow de kar saaf karein": "gently blow / pressure-clean it",
    "seedhi (level) lagi hai": "fitted level",
    "tedhi hone se": "if it is tilted,",
    "pani galat side gir jata hai": "water falls the wrong way",
    "coil par barf jami hai": "ice is stuck on the coil",
    "gandi filter ya kam gas ki nishani": "a sign of a dirty filter or low gas",
    "socket, switch board ya extension": "a socket, switchboard or extension",
    "qareeb gir raha ho": "is falling near",
    "us hisse ka mcb": "that section's MCB",
    "tapakne wale pani ke neeche baalti rakhein": "put a bucket under the leak",
    "farsh sukha rakhein": "keep the floor dry",
    "phisalne ka khatra hai": "there is a slip hazard",
    "deewar ka switch": "wall switch",
    "regulator dono on hain": "and regulator are both ON",
    "main switch": "main switch",
    "main mcb": "main MCB",
    "rescue 1122": "Rescue 1122",
    "sui gas emergency": "Sui Gas emergency",
    "paani": "water",
    "pani": "water",
    "bijli": "electricity",
    "aag": "fire",
    "dhuwa": "smoke",
    "dhuan": "smoke",
    "chingari": "spark",
    "jhatka": "shock",
    "jalne ki smell": "burning smell",
    "jalne ki bu": "burning smell",
    "jalne ki boo": "burning smell",
    "bohat zyada garam": "overheating badly",
    "baar baar trip": "tripping again and again",
    "pipe burst": "pipe burst",
    "flooding": "flooding",
    "gas leak": "gas leak",
    "technician": "technician",
    "electrician": "electrician",
    "plumber": "plumber",
    "appliance": "appliance",
    "switch": "switch",
    "socket": "socket",
    "wiring": "wiring",
    "compressor": "compressor",
    "capacitor": "capacitor",
    "filter": "filter",
    "motor": "motor",
    "pump": "pump",
    "geyser": "geyser",
    "fridge": "fridge",
    "inverter": "inverter",
    "battery": "battery",
    "remote": "remote",
    "valve": "valve",
    "tank": "tank",
    "nali": "drain",
    "pipe": "pipe",
    "leak": "leak",
    "smoke": "smoke",
    "fire": "fire",
    "shock": "shock",
    "karein": "do",
    "karen": "do",
    "karo": "do",
    "karwayein": "have it done",
    "dekhein": "check",
    "dekho": "check",
    "rakhein": "keep",
    "lagayein": "fit",
    "lagao": "fit",
    "nikaal": "remove",
    "nikal": "come out",
    "nikaalein": "remove",
    "dein": "give",
    "daalein": "pour",
    "kholein": "open",
    "chalayein": "run",
    "chalao": "run",
    "hai": "is",
    "hain": "are",
    "nahi": "not",
    "nai": "not",
    "nhi": "not",
    "raha": "",
    "rahi": "",
    "rahe": "",
    "gaya": "gone",
    "gai": "gone",
    "gaye": "gone",
    "hua": "happened",
    "hui": "happened",
    "aur": "and",
    "yeh": "this",
    "woh": "that",
    "us": "that",
    "usay": "it",
    "usko": "it",
    "uska": "its",
    "uski": "its",
    "iski": "its",
    "iska": "its",
    "koi": "any",
    "liye": "for",
    "mein": "in",
    "par": "on",
    "se": "from",
    "ka": "of",
    "ki": "of",
    "ke": "of",
    "ko": "to",
    "neeche": "below",
    "ooper": "above",
    "uper": "above",
    "andar": "inside",
    "bahar": "outside",
    "pehle": "first",
    "phir": "then",
    "khud": "yourself",
    "mat": "do not",
    "band": "off",
    "chalu": "on",
    "kharab": "faulty",
    "pankha": "fan",
    "awaz": "noise",
    "hawa": "air",
    "mitti": "dirt",
    "saaf": "clean",
    "safai": "cleaning",
    "garam": "hot",
    "thanda": "cold",
    "thandi": "cold",
    "haath": "hands",
    "ghar": "home",
    "farsh": "floor",
    "deewar": "wall",
    "chhat": "roof",
    "wali": "",
    "wala": "",
    "wale": "",
    "hisse": "section",
    "hissa": "section",
    "kaam": "work",
    "masla": "issue",
    "theek": "ok",
    "zyada": "too much",
    "kam": "low",
    "dheela": "loose",
    "dheeli": "loose",
    "jam": "stuck",
    "jal": "burn",
    "hone": "being",
    "hota": "happens",
    "hoti": "happens",
    "bhi": "also",
    "tak": "until",
    "saath": "with",
    "wajah": "reason",
    "karke": "after",
    "laga": "installed",
    "lagi": "fitted",
    "nal": "tap",
    "bachon": "children",
    "door": "away",
    "rakhein": "keep",
    "nishani": "sign",
    "hai.": "is.",
    "khatarnak": "dangerous",
    "jaanleva": "life-threatening",
    "geele": "wet",
    "geeli": "wet",
    "sookhi": "dry",
    "sookhe": "dry",
    "ret": "sand",
    "khirki": "window",
    "khirkiyan": "windows",
    "darwaza": "door",
    "darwaze": "doors",
    "kamra": "room",
    "ventilate": "ventilate",
    "dobara on": "turn on again",
    "kabhi": "never",
    "pehle technician check kare": "have a technician check it first",
    "paas mein": "nearby",
    "electrical par": "on electrical parts",
    "ghar walon ko": "family members",
    "us kamre se bahar nikaalein": "take them out of that room",
    "pani mat dalein": "do not pour water",
    "use karein": "use",
    "qabu mein na aaye to": "if it is not under control,",
    "foran call karein": "call immediately",
    "wapas on karne ki koshish": "trying to turn it on again",
    "insulation ya winding jalne": "insulation or winding burning",
    "us point/circuit par": "on that point/circuit",
    "doosra appliance": "another appliance",
    "istemaal band rakhein": "keep it switched off",
    "short circuit": "short circuit",
    "ki nishani hai": "is a sign of",
    "dobara use mat karein": "do not use it again",
    "bachon ko door rakhein": "keep children away",
    "geele haath se": "with wet hands",
    "bilkul mat chhuein": "do not touch at all",
    "body par current aana": "current on the body",
    "earthing fail": "earthing failure",
    "jab tak electrician check na kare": "until an electrician checks it",
    "us appliance ko haath mat lagayein": "do not touch that appliance",
    "kisi ko shock lag jaye to": "if someone gets a shock,",
    "pehle supply off karein": "cut the supply first",
    "phir usay chhuein": "then touch them",
    "rccb (30ma) lagwane ka mashwara zaroor lein": "definitely get an RCCB (30mA) installed",
    "gas valve": "gas valve",
    "khirkiyan kholein": "open the windows",
    "koi switch, light ya mobile on/off mat karein": "do not turn any switch, light or phone on/off",
    "chingari se blast ho sakta hai": "a spark can cause a blast",
    "maachis/lighter bilkul na jalayein": "do not light a match/lighter at all",
    "ghar se bahar nikal jayein": "leave the house",
    "pani aur bijli ka mel": "water mixed with electricity",
    "nange paun mat chalein": "do not walk barefoot",
    "pani ka source band karein": "shut the water source",
    "phir hi safai karein": "only then clean up",
    "main water valve": "main water valve",
    "tank ka valve": "tank valve",
    "emergency plumber bulayein": "call an emergency plumber",
    "pani ka nuksan har minute barhta hai": "water damage increases every minute",
    "thanda hone dein": "let it cool down",
    "zyada garam hona": "overheating",
    "load ya fault": "overload or a fault",
    "kapra/cover mat dalein": "do not put a cloth/cover on it",
    "hawa lagne dein": "let air reach it",
    "baar baar garam ho raha ho to": "if it keeps overheating,",
    "technician se check karwayein": "have a technician inspect it",
    "baar baar wapas on mat karein": "do not keep switching it back ON",
    "yeh fault ka signal hai": "this is a fault signal",
    "isay ignore karna aag ki wajah ban sakta hai": "ignoring it can cause a fire",
    "saare appliances unplug karein": "unplug all appliances",
    "db check karwayein": "have the DB checked",
    "khud db mat kholein": "do not open the DB yourself",
    "appliance ka istemaal foran band kar dein": "stop using the appliance immediately",
    "aage koi bhi test khud na karein": "do not run any further tests yourself",
    "uska mcb / switch off karein": "switch its MCB / switch off",
    "ghar walon, khaas taur par bachon ko us jagah se door rakhein": "keep family members, especially children, away from that area",
    "door se photo/video bana lein": "take a photo/video from a distance",
    "taake technician ko dikha sakein": "so you can show the technician",
    "qareeb na jayein": "do not go near it",
    "dobara on kabhi na karein": "never turn it ON again",
    "ac 220v par chalta hai": "the AC runs on 220V",
    "panel khud mat kholein": "do not open the panel yourself",
}

# extra single tokens
TOKENS = {
    "agar": "if",
    "to": "then",
    "ho": "is",
    "hote": "are",
    "hon": "are",
    "tha": "was",
    "thi": "was",
    "kiye": "done",
    "kia": "did",
    "kya": "what",
    "kyu": "why",
    "kyun": "why",
    "kaise": "how",
    "kese": "how",
    "sab": "all",
    "se": "from",
    "sath": "with",
    "saath": "with",
    "lekin": "but",
    "magar": "but",
    "bohat": "very",
    "bahut": "very",
    "thoda": "a little",
    "thora": "a little",
    "poora": "full",
    "pura": "full",
    "sirf": "only",
    "bilkul": "completely",
    "foran": "immediately",
    "abhi": "now",
    "jab": "when",
    "tab": "then",
    "yahan": "here",
    "wahan": "there",
    "andar": "inside",
    "bahar": "outside",
    "neeche": "below",
    "oopar": "above",
    "ooper": "above",
    "pehle": "first",
    "baad": "after",
    "phir": "then",
    "warna": "otherwise",
    "is liye": "so",
    "isliye": "so",
    "kyunke": "because",
    "kyunki": "because",
    "wajah": "reason",
    "masla": "issue",
    "maslay": "issues",
    "theek": "ok",
    "kharab": "faulty",
    "khrab": "faulty",
    "chalu": "on",
    "chal": "run",
    "chalti": "runs",
    "chalta": "runs",
    "raha": "",
    "rahi": "",
    "rahe": "",
    "gaya": "gone",
    "gayi": "gone",
    "gyi": "gone",
    "gya": "gone",
    "hua": "",
    "hui": "",
    "hue": "",
    "wala": "",
    "wali": "",
    "wale": "",
    "apna": "your",
    "apni": "your",
    "apne": "your",
    "mera": "my",
    "meri": "my",
    "mere": "my",
    "mujhe": "me",
    "hum": "we",
    "aap": "you",
    "un": "those",
    "unke": "their",
    "unka": "their",
    "ye": "this",
    "wo": "that",
    "woh": "that",
    "yeh": "this",
    "koi": "any",
    "kuch": "some",
    "sab": "all",
    "har": "every",
    "bhi": "also",
    "hi": "",
    "na": "not",
    "nahin": "not",
    "nahi": "not",
    "mat": "do not",
    "zaroor": "definitely",
    "shayad": "maybe",
    "aksar": "often",
    "kabhi": "never",
    "hamesha": "always",
    "phir": "then",
    "dobara": "again",
    "khud": "yourself",
    "unplug": "unplug",
    "on": "ON",
    "off": "OFF",
    "mcb": "MCB",
    "rccb": "RCCB",
    "db": "DB",
    "ac": "AC",
    "hvac": "HVAC",
}


def translate(text: str) -> str:
    original = text
    # Keep already-English-looking strings mostly intact if few roman tokens
    low = text
    # Apply long phrases first
    items = sorted(GLOSS.items(), key=lambda kv: len(kv[0]), reverse=True)
    for src, dst in items:
        low = re.sub(r"(?i)\b" + re.escape(src) + r"\b", dst, low)

    def repl_token(m):
        w = m.group(0)
        key = w.lower()
        if key in TOKENS:
            return TOKENS[key]
        if key in GLOSS:
            return GLOSS[key]
        return w

    low = re.sub(r"[A-Za-z]+", repl_token, low)
    low = re.sub(r"\s+", " ", low)
    low = low.replace(" .", ".").replace(" ,", ",").replace(" ?", "?").replace(" !", "!")
    low = re.sub(r"\s+—\s+", " — ", low)
    low = low.strip()
    # Capitalize first letter if latin
    if low and low[0].isalpha():
        low = low[0].upper() + low[1:]
    # If translation barely changed and still has many roman markers, leave a cleaned version
    return low if low else original


def dart_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace("$", "\\$").replace("'", "\\'")


def main():
    root = json.loads(DATASET.read_text(encoding="utf-8"))
    strings = collect(root["diagnostic_engine"])
    pairs = []
    for s in strings:
        en = translate(s)
        if en != s:
            pairs.append((s, en))
        else:
            pairs.append((s, s))
    buf = []
    buf.append("// GENERATED — exact English copies of Dataset.json diagnostic strings.")
    buf.append("// ignore_for_file: lines_longer_than_80_chars")
    buf.append("const Map<String, String> kDiagnosisEn = {")
    for ru, en in pairs:
        buf.append(f"  '{dart_escape(ru)}': '{dart_escape(en)}',")
    buf.append("};")
    buf.append("")
    OUT.write_text("\n".join(buf), encoding="utf-8")
    print("wrote", OUT, "entries", len(pairs))


if __name__ == "__main__":
    main()
